// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251114115314_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Arve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EttevõteId")
                        .HasColumnType("int");

                    b.Property<int>("KoostajaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("KoostatudKuupäev")
                        .HasColumnType("datetime2");

                    b.Property<int>("Käibemaksumäär")
                        .HasColumnType("int");

                    b.Property<DateTime>("Maksetähtaeg")
                        .HasColumnType("datetime2");

                    b.Property<int>("SummaKäibemaksuga")
                        .HasColumnType("int");

                    b.Property<int>("SummaKäibemaksuta")
                        .HasColumnType("int");

                    b.Property<int>("TellijaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EttevõteId");

                    b.HasIndex("KoostajaId");

                    b.HasIndex("TellijaId");

                    b.ToTable("Arved");
                });

            modelBuilder.Entity("backend.Models.Ettevõte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aadress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Registrikood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SebKonto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SwedbankKonto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ettevõtted");
                });

            modelBuilder.Entity("backend.Models.Kasutaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KasutajaTüüp")
                        .HasColumnType("int");

                    b.Property<string>("Nimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kasutajad");

                    b.HasDiscriminator<int>("KasutajaTüüp");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("backend.Models.Produkt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaasHind")
                        .HasColumnType("int");

                    b.Property<string>("Nimetus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProduktTüüp")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Ühik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Produktid");

                    b.HasDiscriminator<string>("ProduktTüüp").HasValue("BaasProdukt");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("backend.Models.Koostaja", b =>
                {
                    b.HasBaseType("backend.Models.Kasutaja");

                    b.Property<string>("Skype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("backend.Models.Tellija", b =>
                {
                    b.HasBaseType("backend.Models.Kasutaja");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("backend.Models.Toode", b =>
                {
                    b.HasBaseType("backend.Models.Produkt");

                    b.Property<int>("ArveId")
                        .HasColumnType("int");

                    b.Property<int>("Hind")
                        .HasColumnType("int");

                    b.Property<int>("Kogus")
                        .HasColumnType("int");

                    b.HasIndex("ArveId");

                    b.HasDiscriminator().HasValue("ArveToode");
                });

            modelBuilder.Entity("backend.Models.Arve", b =>
                {
                    b.HasOne("backend.Models.Ettevõte", "Ettevõte")
                        .WithMany()
                        .HasForeignKey("EttevõteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Koostaja", "Koostaja")
                        .WithMany()
                        .HasForeignKey("KoostajaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Tellija", "Tellija")
                        .WithMany()
                        .HasForeignKey("TellijaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ettevõte");

                    b.Navigation("Koostaja");

                    b.Navigation("Tellija");
                });

            modelBuilder.Entity("backend.Models.Toode", b =>
                {
                    b.HasOne("backend.Models.Arve", "Arve")
                        .WithMany("Tooted")
                        .HasForeignKey("ArveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arve");
                });

            modelBuilder.Entity("backend.Models.Arve", b =>
                {
                    b.Navigation("Tooted");
                });
#pragma warning restore 612, 618
        }
    }
}
